<?php
$lang = array(
  // General
  'page_title' => 'Covinova - Your Home, Your Future',
  'fuscvam_icon_alt' => 'FUSCVAM icon',
  'cooperative_icon_alt' => 'Cooperative icon',

  // Navbar
  'nav_home' => 'Home',
  'nav_cooperative' => 'Cooperative',
  'nav_software' => 'Our Software',
  'nav_testimonials' => 'Testimonials',
  'nav_application' => 'Membership Application',
  'language_label' => 'Language:',
  'lang_spanish' => 'Spanish',
  'lang_english' => 'English',
  'nav_login' => 'Log In',

  // Hero Section
  'hero_title_part1' => 'Your ',
  'hero_title_gradient' => 'Own Home',
  'hero_title_part2' => 'Is Possible in Uruguay',
  'hero_description' => 'Join our housing cooperative and get your own home with our savings and loan system. Plus, manage everything with our specialized software.',
  'btn_learn_cooperative' => 'Learn About the Cooperative',
  'btn_about_software' => 'About Our Software',
  'stat_families' => 'Families with homes',
  'stat_experience' => 'Years of experience',
  'stat_transparency' => 'Transparency',
  'card_key_future' => 'Key to the future',
  'card_digital_records' => 'Digital records',
  'card_united_community' => 'United community',

  // Cooperative Section
  'cooperative_section_title' => 'Housing Cooperative',
  'cooperative_section_subtitle' => 'The safest path to your own home',
  'feature_savings_title' => 'Savings System',
  'feature_savings_description' => 'Save systematically with affordable installments and get your home without the need for large initial capital.',
  'feature_mutual_aid_title' => 'Mutual Aid',
  'feature_mutual_aid_description' => 'We work together in construction, reducing costs and strengthening community ties.',
  'feature_collective_ownership_title' => 'Collective Ownership',
  'feature_collective_ownership_description' => 'Collective ownership system that guarantees housing permanence and accessibility.',
  'feature_premium_locations_title' => 'Premium Locations',
  'feature_premium_locations_description' => 'Strategically located land in Montevideo and the interior of the country with all services.',

  // Software Section
  'software_section_title' => 'Management Software',
  'software_section_subtitle' => 'We have advanced technology to help you manage your housing in our cooperative',
  'software_member_management_title' => 'Member Management',
  'software_member_management_description' => 'Manage complete information of all cooperative members, payment verification and digitization, to facilitate management.',
  'software_financial_control_title' => 'Financial Control',
  'software_financial_control_description' => 'Detailed tracking of income, expenses, fees, and personal records in real time.',
  'software_smart_reports_title' => 'Smart Reports',
  'software_smart_reports_description' => 'Generate automatic reports for assemblies, members, and cooperative construction works.',
  'software_cloud_access_title' => 'Cloud Access',
  'software_cloud_access_description' => 'Access your information from any device, securely and at any time.',

  // Testimonials Section
  'testimonials_section_title' => 'What our cooperative members say',
  'testimonials_section_subtitle' => 'Real stories of families who achieved their home',
  'testimonial_1_text' => '"I\'ve been with Covinova for 3 months, I love it. Everything in one place to manage, a cooperative and transparent environment. An incredible experience."',
  'testimonial_1_author' => 'María González',
  'testimonial_1_role' => 'Cooperative Member since 2018',
  'testimonial_2_text' => '"The mutual aid experience was incredible. We didn\'t just build houses, we built a community. The software facilitated all management."',
  'testimonial_2_author' => 'Joaquin Rodríguez',
  'testimonial_2_role' => 'Cooperative Member since 2019',
  'testimonial_3_text' => '"As a cooperative administrator, Nexora\'s software changed our lives. Everything automated and transparent for all members."',
  'testimonial_3_author' => 'Ana Martínez',
  'testimonial_3_role' => 'Administrator',

  // Contact Section
  'contact_section_title' => 'Ready for your own home?',
  'contact_section_subtitle' => 'Schedule an appointment and start your journey to your own home',
  'requirements_title' => 'Requirements to Join',
  'requirements_subtitle' => 'These are the basic requirements to be part of the cooperative:',
  'req_1' => 'Be of legal age (18 years or older).',
  'req_2' => 'Be a legal resident in Uruguay.',
  'req_3' => 'Have a minimum monthly income of 30 Indexed Units.',
  'req_4' => 'Commit to the savings and mutual aid system.',
  'req_5' => 'Complete the application and provide required documents.',
  'form_placeholder_first_name' => 'First Name',
  'form_placeholder_last_name' => 'Last Name',
  'form_placeholder_email' => 'Your Email',
  'form_placeholder_dob' => 'Date of Birth',
  'form_placeholder_phone' => 'Your contact phone: 095123456',
  'form_placeholder_id' => 'Your ID',
  'form_submit_button' => 'Apply for Membership',
  'form_error_message' => 'There was an error with your application',
  'form_success_message' => 'Your application was sent successfully',

  // About Us Section
  'about_us_title' => 'About Us',
  'about_us_subtitle' => 'Mutual Aid Housing Cooperative',
  'about_us_heading' => 'Mutual aid housing cooperative in Uruguay',
  'about_us_paragraph_1' => 'At Covinova, our mission is to provide dignified housing to people who need it. To achieve this, we are committed to mutual aid, solidarity, and transparency. Our savings and loan system allows us to provide affordable and quality housing to our members.',
  'about_us_paragraph_2' => 'Our goal is to strengthen the community and support people who want to improve their quality of life. Therefore, we offer a sustainable and responsible housing model that adapts to the needs and possibilities of each person.',
  'contact_location_title' => 'Location',
  'contact_location_address' => 'Av. 18 de Julio 1234<br>Montevideo, Uruguay',
  'contact_phone_title' => 'Phone',
  'contact_phone_number' => '+598 93 395 215',
  'contact_email_title' => 'Email',
  'contact_email_address' => 'covinovahlp@gmail.com',
  'cooperative_image_alt' => 'Cooperative image',
  'cooperative_image_expanded_alt' => 'Expanded cooperative image',

  // Footer
  'footer_description' => 'Building homes, strengthening communities. Your trusted housing cooperative in Uruguay.',
  'footer_info_title' => 'Information',
  'footer_link_about_us' => 'About Us',
  'footer_link_faq' => 'Frequently Asked Questions',
  'footer_link_terms' => 'Terms and Conditions',
  'footer_link_privacy' => 'Privacy Policy',
  'footer_contact_title' => 'Contact',
  'footer_contact_location' => 'Montevideo, Uruguay',
  'footer_contact_phone' => '+598 93 395215',
  'footer_contact_email' => 'covinovahlp@gmail.com',
  'footer_copyright' => '&copy; 2025 Covinova Uruguay. All rights reserved.',
);
?>
