<?php
$lang = array(
  // General
  'page_title' => 'Covinova - Tu Hogar, Tu Futuro',
  'fuscvam_icon_alt' => 'FUSCVAM icono',
  'cooperative_icon_alt' => 'Cooperativa icono',

  // Navbar
  'nav_home' => 'Inicio',
  'nav_cooperative' => 'Cooperativa',
  'nav_software' => 'Nuestro Software',
  'nav_testimonials' => 'Testimonios',
  'nav_application' => 'Solicitud de ingreso',
  'language_label' => 'Idioma:',
  'lang_spanish' => 'Español',
  'lang_english' => 'English',
  'nav_login' => 'Iniciar Sesión',

  // Hero Section
  'hero_title_part1' => 'Tu ',
  'hero_title_gradient' => 'Hogar Propio',
  'hero_title_part2' => 'Es Posible en Uruguay',
  'hero_description' => 'Únete a nuestra cooperativa de vivienda y accede a tu casa propia con nuestro sistema de ahorro y préstamo. Además, gestiona todo con nuestro software especializado.',
  'btn_learn_cooperative' => 'Conocer Cooperativa',
  'btn_about_software' => 'Acerca de nuestro Software',
  'stat_families' => 'Familias con hogar',
  'stat_experience' => 'Años de experiencia',
  'stat_transparency' => 'Transparencia',
  'card_key_future' => 'Clave para el futuro',
  'card_digital_records' => 'Registros digitales',
  'card_united_community' => 'Comunidad unida',

  // Cooperative Section
  'cooperative_section_title' => 'Cooperativa de Vivienda',
  'cooperative_section_subtitle' => 'El camino más seguro hacia tu hogar propio',
  'feature_savings_title' => 'Sistema de Ahorro',
  'feature_savings_description' => 'Ahorra de forma sistemática con cuotas accesibles y obtén tu vivienda sin necesidad de grandes capitales iniciales.',
  'feature_mutual_aid_title' => 'Ayuda Mutua',
  'feature_mutual_aid_description' => 'Trabajamos juntos en la construcción, reduciendo costos y fortaleciendo los lazos comunitarios.',
  'feature_collective_ownership_title' => 'Propiedad Colectiva',
  'feature_collective_ownership_description' => 'Sistema de propiedad colectiva que garantiza la permanencia y accesibilidad de la vivienda.',
  'feature_premium_locations_title' => 'Ubicaciones Premium',
  'feature_premium_locations_description' => 'Terrenos estratégicamente ubicados en Montevideo y el interior del país con todos los servicios.',

  // Software Section
  'software_section_title' => 'Software de Gestión',
  'software_section_subtitle' => 'Contamos con tecnología avanzada para ayudarte a administrar tu vivienda en nuestra cooperativa',
  'software_member_management_title' => 'Gestión de Socios',
  'software_member_management_description' => 'Administra información completa de todos los cooperativistas, comprobación y digitalización de pagos, para facilitar la gestión.',
  'software_financial_control_title' => 'Control Financiero',
  'software_financial_control_description' => 'Seguimiento detallado de ingresos, egresos, cuotas y registros personales en tiempo real.',
  'software_smart_reports_title' => 'Reportes Inteligentes',
  'software_smart_reports_description' => 'Genera reportes automáticos para asambleas, socios y reportes de las obras de la cooperativa.',
  'software_cloud_access_title' => 'Acceso en la Nube',
  'software_cloud_access_description' => 'Accede a tu información desde cualquier dispositivo, de forma segura y en cualquier momento.',

  // Testimonials Section
  'testimonials_section_title' => 'Lo que dicen nuestros cooperativistas',
  'testimonials_section_subtitle' => 'Historias reales de familias que lograron su hogar',
  'testimonial_1_text' => '"LLevo 3 meses dentro de covinova, me encanta. Todo en un solo lugar para administrar, un ambiente cooperativo y transparente. Una experiencia increíble."',
  'testimonial_1_author' => 'María González',
  'testimonial_1_role' => 'Cooperativista desde 2018',
  'testimonial_2_text' => '"La experiencia de ayuda mutua fue increíble. No solo construimos casas, construimos una comunidad. El software facilitó toda la gestión."',
  'testimonial_2_author' => 'Joaquin Rodríguez',
  'testimonial_2_role' => 'Cooperativista desde 2019',
  'testimonial_3_text' => '"Como administrador de la cooperativa, el software de Nexora nos cambió la vida. Todo automatizado y transparente para todos los socios."',
  'testimonial_3_author' => 'Ana Martínez',
  'testimonial_3_role' => 'Administradora',

  // Contact Section
  'contact_section_title' => '¿Listo para tu hogar propio?',
  'contact_section_subtitle' => 'Agenda una cita y comienza tu camino hacia tu hogar propio',
  'requirements_title' => 'Requisitos para Ingresar',
  'requirements_subtitle' => 'Estos son los requisitos básicos para ser parte de la cooperativa:',
  'req_1' => 'Ser mayor de edad (18 años o más).',
  'req_2' => 'Ser residente legal en Uruguay.',
  'req_3' => 'Contar con un ingreso mensual mínimo de 30 Unidades Indexadas.',
  'req_4' => 'Comprometerse con el sistema de ahorro y ayuda mutua.',
  'req_5' => 'Completar la solicitud y proporcionar documentos requeridos.',
  'form_placeholder_first_name' => 'Primer nombre',
  'form_placeholder_last_name' => 'Primer apellido',
  'form_placeholder_email' => 'Tu email',
  'form_placeholder_dob' => 'Fecha de nac.',
  'form_placeholder_phone' => 'Tu teléfono de contacto: 095123456',
  'form_placeholder_id' => 'Tu CI',
  'form_submit_button' => 'Solicitar ingreso',
  'form_error_message' => 'Hubo un error con tu solicitud',
  'form_success_message' => 'Tu solicitud fue enviada con exito',

  // About Us Section
  'about_us_title' => 'Sobre Nosotros',
  'about_us_subtitle' => 'Cooperativa de Vivienda de Ayuda Mutua',
  'about_us_heading' => 'Cooperativa de viviendas de ayuda mutua en Uruguay',
  'about_us_paragraph_1' => 'En Covinova, nuestra misión es brindar una vivienda digna a las personas que la necesitan. Para lograr esto, estamos comprometidos con la ayuda mutua, la solidaridad y la transparencia. Nuestro sistema de ahorro y préstamo nos permite brindar viviendas asequibles y de calidad a nuestros socios.',
  'about_us_paragraph_2' => 'Nuestro objetivo es fortalecer la comunidad y apoyar a las personas que quieren mejorar su calidad de vida. Por eso, ofrecemos un modelo de vivienda sostenible y responsable, que se ajusta a las necesidades y posibilidades de cada persona.',
  'contact_location_title' => 'Ubicación',
  'contact_location_address' => 'Av. 18 de Julio 1234<br>Montevideo, Uruguay',
  'contact_phone_title' => 'Teléfono',
  'contact_phone_number' => '+598 93 395 215',
  'contact_email_title' => 'Email',
  'contact_email_address' => 'covinovahlp@gmail.com',
  'cooperative_image_alt' => 'Imagen de la cooperativa',
  'cooperative_image_expanded_alt' => 'Imagen ampliada de la cooperativa',

  // Footer
  'footer_description' => 'Construyendo hogares, fortaleciendo comunidades. Tu cooperativa de vivienda de confianza en Uruguay.',
  'footer_info_title' => 'Información',
  'footer_link_about_us' => 'Sobre Nosotros',
  'footer_link_faq' => 'Preguntas Frecuentes',
  'footer_link_terms' => 'Términos y Condiciones',
  'footer_link_privacy' => 'Política de Privacidad',
  'footer_contact_title' => 'Contacto',
  'footer_contact_location' => 'Montevideo, Uruguay',
  'footer_contact_phone' => '+598 93 395215',
  'footer_contact_email' => 'covinovahlp@gmail.com',
  'footer_copyright' => '&copy; 2025 Covinova Uruguay. Todos los derechos reservados.',
);
?>
